FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG PSI_API_KEY
ARG ADS_DEVELOPER_TOKEN
ARG ADS_MCC_ID

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV PSI_API_KEY=$PSI_API_KEY
ENV ADS_DEVELOPER_TOKEN=$ADS_DEVELOPER_TOKEN
ENV ADS_MCC_ID=$ADS_MCC_ID

RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]